# Generated by Django 3.1.4 on 2020-12-10 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20201210_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('SortCode', models.IntegerField()),
                ('AccountNumber', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Direction', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='Out', max_length=10)),
                ('TransactionTime', models.CharField(max_length=50)),
                ('Comment', models.CharField(blank=True, max_length=200)),
                ('NewBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Destination', models.CharField(max_length=50)),
                ('Category', models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Drink', 'Drink'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Clothing', 'Clothing'), ('ATM Withdrawal', 'ATM Withdrawal'), ('ATM Deposit', 'ATM Deposit'), ('Cheque Deposit', 'Cheque Deposit'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
                ('Payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.payee')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardFrozen', models.BooleanField(default=False)),
                ('CardNum', models.BigIntegerField()),
                ('ExpiryDate', models.DateField()),
                ('CVC', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
            ],
        ),
    ]
