# Generated by Django 3.1.4 on 2020-12-27 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Direction', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='Out', max_length=10)),
                ('TransactionTime', models.CharField(max_length=50)),
                ('Comment', models.CharField(blank=True, max_length=200)),
                ('NewBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Termini', models.CharField(max_length=50)),
                ('Category', models.CharField(choices=[('Dining Out', 'Dining Out'), ('Food Shopping', 'Food Shopping'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Clothing', 'Clothing'), ('Rent', 'Rent'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], max_length=20)),
                ('Method', models.CharField(choices=[('ATM Withdrawal', 'Atm Withdrawal'), ('ATM Deposit', 'Atm Deposit'), ('Cheque Deposit', 'Cheque Deposit'), ('Bank Transfer', 'Bank Transfer'), ('Card Transaction', 'Card Transaction')], default='Bank Transfer', max_length=20)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
                ('Payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyPot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Money Pot', max_length=100)),
                ('target_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pot_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardFrozen', models.BooleanField(default=False)),
                ('CardNum', models.BigIntegerField(unique=True)),
                ('ExpiryDate', models.DateField()),
                ('CVC', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
            ],
        ),
    ]
