# Generated by Django 3.1.4 on 2020-12-09 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('SortCode', models.IntegerField()),
                ('AccountNumber', models.IntegerField()),
                ('Balance', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('AccountFrozen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('SortCode', models.IntegerField()),
                ('AccountNumber', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Direction', models.BooleanField(default=0)),
                ('DateTime', models.DateTimeField(editable=False)),
                ('Comment', models.CharField(blank=True, max_length=200)),
                ('NewBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Destination', models.CharField(max_length=50)),
                ('Category', models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Payee Transfer', 'Payee'), ('Other', 'Other')], default='Other', max_length=20)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.customer')),
                ('Payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.payee')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardFrozen', models.BooleanField(default=False)),
                ('CardNum', models.IntegerField()),
                ('ExpiryDate', models.DateTimeField()),
                ('CVC', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.customer')),
            ],
        ),
    ]
