# Generated by Django 3.1.4 on 2020-12-11 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionTime',
            field=models.CharField(default=datetime.datetime(2020, 12, 11, 14, 15, 17, 455733, tzinfo=utc), max_length=50),
        ),
    ]
