# Generated by Django 3.1.4 on 2020-12-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='CVC',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TransactionTime',
            field=models.DateTimeField(),
        ),
    ]
