# Generated by Django 3.1.4 on 2020-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201210_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('ATM Withdrawal', 'ATM Withdrawal'), ('Drink', 'Drink'), ('Clothing', 'Clothing'), ('Bank Transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Direction',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='Out', max_length=10),
        ),
    ]
