# Generated by Django 3.1.4 on 2020-12-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201227_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='MaskCardNum',
            field=models.CharField(default='xxxxxxxxxxxxxxxx', max_length=16),
        ),
    ]
