# Generated by Django 3.1.4 on 2020-12-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201210_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Drink', 'Drink'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Clothing', 'Clothing'), ('ATM Withdrawal', 'ATM Withdrawal'), ('ATM Deposit', 'ATM Deposit'), ('Cheque Deposit', 'Cheque Deposit'), ('Bank Transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
