# Generated by Django 3.1.4 on 2020-12-14 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201212_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionTime',
            field=models.CharField(default=datetime.datetime(2020, 12, 14, 18, 41, 21, 436804, tzinfo=utc), max_length=50),
        ),
    ]
