# Generated by Django 3.1.4 on 2020-12-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201212_2245'),
        ('dashboard', '0003_auto_20201212_1343'),
    ]

    operations = [
    ]
