# Generated by Django 3.1.4 on 2020-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201210_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='CardNum',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='ExpiryDate',
            field=models.DateField(),
        ),
    ]
