# Generated by Django 3.1.4 on 2020-12-14 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201214_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionTime',
            field=models.CharField(default=datetime.datetime(2020, 12, 14, 20, 1, 34, 990514, tzinfo=utc), max_length=50),
        ),
    ]
