# Generated by Django 3.1.4 on 2020-12-10 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201210_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='DateTime',
        ),
        migrations.AddField(
            model_name='transaction',
            name='TransactionTime',
            field=models.CharField(default=datetime.datetime(2020, 12, 10, 15, 22, 39, 66161, tzinfo=utc), editable=False, max_length=50),
        ),
    ]
