# Generated by Django 3.1.4 on 2020-12-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201230_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
