# Generated by Django 3.1.4 on 2020-12-14 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201213_1711'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20201213_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='Customer',
        ),
        migrations.AddField(
            model_name='payee',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payee',
            name='PayeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
    ]
