# Generated by Django 3.1.4 on 2020-12-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20201214_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Method',
            field=models.CharField(choices=[('ATM Withdrawal', 'Atm Withdrawal'), ('ATM Deposit', 'Atm Deposit'), ('Cheque Deposit', 'Cheque Deposit'), ('Bank Transfer', 'Bank Transfer'), ('Card Transaction', 'Card Transaction')], default='Bank Transfer', max_length=20),
        ),
    ]
