# Generated by Django 3.1.4 on 2020-12-16 13:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_transaction_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Destination',
            new_name='Termini',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
    ]
