# Generated by Django 3.1.4 on 2021-01-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210102_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
