# Generated by Django 3.1.4 on 2021-01-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_livechat_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechat',
            name='perm_granted',
            field=models.BooleanField(default=False),
        ),
    ]
