# Generated by Django 3.1.4 on 2020-12-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201213_1711'),
        ('dashboard', '0011_auto_20201216_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
    ]
