# Generated by Django 3.1.5 on 2021-01-13 21:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_livechat_perm_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneypot',
            name='target_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
