# Generated by Django 3.1.5 on 2021-01-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210113_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Category',
            field=models.CharField(choices=[('Dining Out', 'Dining Out'), ('Food Shopping', 'Food Shopping'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Clothing', 'Clothing'), ('Rent', 'Rent'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], max_length=70),
        ),
    ]
