# Generated by Django 3.1.5 on 2021-01-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=9, null=True),
        ),
    ]
