# Generated by Django 3.1.4 on 2020-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sort_code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
