# Generated by Django 3.1.4 on 2020-12-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201210_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sort_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
