# Generated by Django 3.1.4 on 2020-12-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201210_1634'),
    ]

